# SPDX-FileCopyrightText: Copyright (c) 2012-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

FROM yegor256/java:0.0.1
LABEL description="RULTOR image for simple Python+Pip projects"
LABEL version="0.0.1"

SHELL ["/bin/bash", "-e", "-c", "-o", "pipefail"]

ENV PYTHON_VERSION=3.12.0
RUN /usr/bin/install-python.sh
